In [2]:
!pip install spacy

# New Section

# New Section

In [3]:
import spacy

In [4]:
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 1.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [5]:
nlp = spacy.load("en_core_web_lg")

In [6]:
doc = nlp("dog cat banana jkfgsjg")

for token in doc:
  print(token.text, "vector:", token.has_vector, "OOV:", token.is_oov)

dog vector: True OOV: False
cat vector: True OOV: False
banana vector: True OOV: False
jkfgsjg vector: False OOV: True


In [7]:
doc[0].vector

array([-4.0176e-01,  3.7057e-01,  2.1281e-02, -3.4125e-01,  4.9538e-02,
        2.9440e-01, -1.7376e-01, -2.7982e-01,  6.7622e-02,  2.1693e+00,
       -6.2691e-01,  2.9106e-01, -6.7270e-01,  2.3319e-01, -3.4264e-01,
        1.8311e-01,  5.0226e-01,  1.0689e+00,  1.4698e-01, -4.5230e-01,
       -4.1827e-01, -1.5967e-01,  2.6748e-01, -4.8867e-01,  3.6462e-01,
       -4.3403e-02, -2.4474e-01, -4.1752e-01,  8.9088e-02, -2.5552e-01,
       -5.5695e-01,  1.2243e-01, -8.3526e-02,  5.5095e-01,  3.6410e-01,
        1.5361e-01,  5.5738e-01, -9.0702e-01, -4.9098e-02,  3.8580e-01,
        3.8000e-01,  1.4425e-01, -2.7221e-01, -3.7016e-01, -1.2904e-01,
       -1.5085e-01, -3.8076e-01,  4.9583e-02,  1.2755e-01, -8.2788e-02,
        1.4339e-01,  3.2537e-01,  2.7226e-01,  4.3632e-01, -3.1769e-01,
        7.9405e-01,  2.6529e-01,  1.0135e-01, -3.3279e-01,  4.3117e-01,
        1.6687e-01,  1.0729e-01,  8.9418e-02,  2.8635e-01,  4.0117e-01,
       -3.9222e-01,  4.5217e-01,  1.3521e-01, -2.8878e-01, -2.28

In [8]:
doc[1].vector

array([-0.15067  , -0.024468 , -0.23368  , -0.23378  , -0.18382  ,
        0.32711  , -0.22084  , -0.28777  ,  0.12759  ,  1.1656   ,
       -0.64163  , -0.098455 , -0.62397  ,  0.010431 , -0.25653  ,
        0.31799  ,  0.037779 ,  1.1904   , -0.17714  , -0.2595   ,
       -0.31461  ,  0.038825 , -0.15713  , -0.13484  ,  0.36936  ,
       -0.30562  , -0.40619  , -0.38965  ,  0.3686   ,  0.013963 ,
       -0.6895   ,  0.004066 , -0.1367   ,  0.32564  ,  0.24688  ,
       -0.14011  ,  0.53889  , -0.80441  , -0.1777   , -0.12922  ,
        0.16303  ,  0.14917  , -0.068429 , -0.33922  ,  0.18495  ,
       -0.082544 , -0.46892  ,  0.39581  , -0.13742  , -0.35132  ,
        0.22223  , -0.144    , -0.048287 ,  0.3379   , -0.31916  ,
        0.20526  ,  0.098624 , -0.23877  ,  0.045338 ,  0.43941  ,
        0.030385 , -0.013821 , -0.093273 , -0.18178  ,  0.19438  ,
       -0.3782   ,  0.70144  ,  0.16236  ,  0.0059111,  0.024898 ,
       -0.13613  , -0.11425  , -0.31598  , -0.14209  ,  0.0281

In [9]:
doc[3].vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [10]:
base_token = nlp("sandwich")
base_token

sandwich

In [11]:
doc = nlp("bread sandwich burger car tiger human rice food")

for token in doc:
  print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

bread <-> sandwich: 0.6874560117721558
sandwich <-> sandwich: 1.0
burger <-> sandwich: 0.767081618309021
car <-> sandwich: 0.1664874404668808
tiger <-> sandwich: 0.1713561713695526
human <-> sandwich: 0.14466442167758942
rice <-> sandwich: 0.46796026825904846
food <-> sandwich: 0.5090628862380981


In [12]:
def similar_words(base_word, word_to_compare):
  base_token = nlp(base_word)
  doc = nlp(word_to_compare)
  for token in doc:
      print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

In [13]:
similar_words("iphone", "apple samsung iphone dog cat banana")

apple <-> iphone: 0.6339781284332275
samsung <-> iphone: 0.6678677797317505
iphone <-> iphone: 1.0
dog <-> iphone: 0.1743103712797165
cat <-> iphone: 0.21171651780605316
banana <-> iphone: 0.19600526988506317


In [14]:
king = nlp.vocab["king"].vector
man = nlp.vocab["man"].vector
woman = nlp.vocab["woman"].vector
queen = nlp.vocab["queen"].vector

result = king - man + woman

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result], [queen])

array([[0.78808445]], dtype=float32)

In [16]:
france = nlp.vocab["France"].vector
paris = nlp.vocab["Paris"].vector
berlin = nlp.vocab["Berlin"].vector
germany = nlp.vocab["Germany"].vector

result = france - paris + berlin

cosine_similarity([result], [germany])

array([[0.78090745]], dtype=float32)

NLP: Text Classification using Spacy word Embeddings¶
end-to-end project: fake and real news data

In [17]:
# mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [18]:
import pandas as pd
#import os
#root_dir = "/content/drive/My Drive/Colab Notebooks/"
#os.chdir(root_dir)

In [19]:

   file_path = '/content/drive/My Drive/Colab Notebooks/fake_or_real_news.csv' # Replace with your file path

   df = pd.read_csv(file_path)
   print(df.head(10))


      id                                              title  \
0   8476                       You Can Smell Hillary’s Fear   
1  10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2   3608        Kerry to go to Paris in gesture of sympathy   
3  10142  Bernie supporters on Twitter erupt in anger ag...   
4    875   The Battle of New York: Why This Primary Matters   
5   6903                                        Tehran, USA   
6   7341  Girl Horrified At What She Watches Boyfriend D...   
7     95                  ‘Britain’s Schindler’ Dies at 106   
8   4869  Fact check: Trump and Clinton at the 'commande...   
9   2909  Iran reportedly makes new push for uranium con...   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      6335 non-null   int64 
 1   title   6335 non-null   object
 2   text    6335 non-null   object
 3   label   6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [21]:
df.shape

(6335, 4)

In [22]:
df['label'].value_counts()

label
REAL    3171
FAKE    3164
Name: count, dtype: int64

In [28]:
df['label_num'] = df['label'].map(
    {
     'FAKE': 0,
     'REAL':1
    } )

In [29]:
print(df.head(10))

      id                                              title  \
0   8476                       You Can Smell Hillary’s Fear   
1  10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2   3608        Kerry to go to Paris in gesture of sympathy   
3  10142  Bernie supporters on Twitter erupt in anger ag...   
4    875   The Battle of New York: Why This Primary Matters   
5   6903                                        Tehran, USA   
6   7341  Girl Horrified At What She Watches Boyfriend D...   
7     95                  ‘Britain’s Schindler’ Dies at 106   
8   4869  Fact check: Trump and Clinton at the 'commande...   
9   2909  Iran reportedly makes new push for uranium con...   

                                                text label  label_num  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL          1  
3  — Kaydee King (

In [30]:
df['label_num'].value_counts()

label_num
1    3171
0    3164
Name: count, dtype: int64

In [31]:
df['vector'] = df['text'].apply(lambda text: nlp(text).vector)

In [33]:
len(df)

6335

In [34]:
print(df.head())

      id                                              title  \
0   8476                       You Can Smell Hillary’s Fear   
1  10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2   3608        Kerry to go to Paris in gesture of sympathy   
3  10142  Bernie supporters on Twitter erupt in anger ag...   
4    875   The Battle of New York: Why This Primary Matters   

                                                text label  label_num  \
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE          0   
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE          0   
2  U.S. Secretary of State John F. Kerry said Mon...  REAL          1   
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE          0   
4  It's primary day in New York and front-runners...  REAL          1   

                                              vector  
0  [-0.06343732, 0.11896122, -0.067684345, -0.018...  
1  [-0.017111547, 0.13953958, -0.05576232, 0.0063...  
2  [-0.018148802,

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split (
    df.vector.values,
    df.label_num,
    test_size = 0.2,
    random_state = 42
)

In [36]:
X_train.shape

(5068,)

In [37]:
X_test.shape

(1267,)

In [38]:
import numpy as np

X_train_stack = np.stack(X_train)
X_test_stack = np.stack(X_test)

In [39]:
print(X_train_stack.shape)
print(X_test_stack.shape)

(5068, 300)
(1267, 300)


In [40]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_stack_sc = scaler.fit_transform(X_train_stack)
X_test_stack_sc = scaler.transform(X_test_stack)


model.fit(X_train_stack_sc, y_train)

MultinomialNB()

In [41]:
y_pred = model.predict(X_test_stack_sc)
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [42]:
y_test

1357    0
2080    0
2718    0
812     0
4886    0
       ..
1512    0
57      1
6092    1
3403    1
292     1
Name: label_num, Length: 1267, dtype: int64

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7853196527229677

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.82      0.79       628
           1       0.81      0.75      0.78       639

    accuracy                           0.79      1267
   macro avg       0.79      0.79      0.79      1267
weighted avg       0.79      0.79      0.79      1267



In [45]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[513, 115],
       [157, 482]])